### ISSUE TITLE
Bug in simplification

### ISSUE THREAD

**Issue by mudbri** [ravel-net/pyotr#18]
There is a bug in z3smt.py when simplification is off. Test 3 in [unit_tests.py](https://github.com/ravel-net/pyotr/blob/eba57adf2561d32682a34bc87d9cce73cb5b94a0/Core/Homomorphism/Datalog/unit_tests.py#L39) fails when simplification is on with the following error code. This is not urgent since it turning simplification off does not violate correctness.

```
Traceback (most recent call last):
  File "unit_tests.py", line 43, in <module>
    program1.minimize()
  File "./program.py", line 151, in minimize
    contained = self.contains_rule(rule_with_deleted_atom)
  File "./program.py", line 112, in contains_rule
    changed = self.execute(conn)
  File "./program.py", line 74, in execute
    DB_changes = rule.execute(conn)
  File "./rule.py", line 326, in execute
    return self.run_with_faure(conn, self.sql)
  File "./rule.py", line 576, in run_with_faure
    FaureEvaluation(conn, program_sql, additional_condition=",".join(self._additional_constraints), output_table="output", domains=self._domains, reasoning_engine=self._reasoning_engine, reasoning_sort=self._reasoning_type, simplication_on=self._simplication_on, information_on=False)
  File "../faure_translator/faure_evaluation.py", line 121, in __init__
    self._simplification_z3()
  File "../faure_translator/faure_evaluation.py", line 303, in _simplification_z3
    has_redun, result = self._z3Smt.has_redundancy(row[1])
  File "../../../reasoning/Z3/z3smt.py", line 241, in has_redundancy
    c = "Not(And({}))".format(", ".join(subset_prcd_conditions))
TypeError: sequence item 0: expected str instance, BoolRef found
```

**Comment by lanfangping** [comment]
Fixed in commit d5f7bc800f85b0a145b669b4a1f9aabd2bef48af
